### ISSUE TITLE
Loose connection

### ISSUE THREAD

**Issue by kevinsimper** [polonskiy/crowdr#1]
In the readme it says "As you can see, server recreated first. It means that client will lost connection."

That does not make sense, because the first example is the exact same as the one after. The server is started first and then the client is started after.

Also the sentence has to either be

It means that **the** client will **have** lost connection

OR

It means that **the** client will **loose** the connection.

Both means two completely different things.

I guess you want to say something about that the client has a moment where it can't access the server and you want to avoid that by stopping in reverse order of how they were started to prevent that the link die, before it is recreated.

**Comment by polonskiy** [comment]
Thanks. English is not my native language. Feel free to send pull requests.

**Comment by kevinsimper** [comment]
But what do you mean? :)

**Comment by polonskiy** [comment]
Maybe example from readme is too abstract.

Lets imagine that we have the server listening on port 1000 and the client. `docker-compose up -d` starts the server a then starts the client. The client connects to the server and keeps the connection open. Second run of `docker-compose up -d` breaks the connection, because the server goes down first.

**Comment by kevinsimper** [comment]
But is that a problem? The client goes down just after, merely a second later?

**Comment by polonskiy** [comment]
It depends on application.

> The client goes down just after, merely a second later?

If application does not handle signals properly, it can be [10 seconds](https://docs.docker.com/reference/commandline/cli/#stop)

I think that graceful stop is better.
