### ISSUE TITLE
Happy New Year!

### ISSUE THREAD

**Issue by polonskiy** [polonskiy/crowdr#14]
Thanks for your contributions! You are awesome!
Happy New Year! :santa: :christmas_tree: :gift: 
@coderofsalvation
@byrnedo
@superm00s
@marcinwaldowski

**Comment by byrnedo** [comment]
Happy new year too :)

**Comment by marcinwaldowski** [comment]
Happy new year :)

**Comment by coderofsalvation** [comment]
happy new year everyone!
