### ISSUE TITLE
Enable inclusion in other scripts

### ISSUE THREAD

**Issue by BitFis** [polonskiy/crowdr#26]
Hey,

Love crowdr, it helps me out greatly. But in some cases I would like to customize some things.
Would it be fine to change the script, so it will only run if it is called directly? 
Here an example: https://github.com/bashup/mdsh/blob/master/bin/mdsh#L280

This would enable anyone to customize the script easily and override funtions if needed.

If that is appriciated I would do a pull request for the change.

Thanks

**Comment by polonskiy** [comment]
Hi. Can you please show me example of what you want to achieve?

**Comment by BitFis** [comment]
Since I have a container with a special bash interface, I would like to override the `crowdr_command_exec` and
`crowdr_command_shell` for this specific container.

This would have locked like this:

```
#!/bin/bash

. ../crowdr/crowdr

crowdr_command_shell() {
    if <Specific container> then
        $crowdr_debug docker exec \
             --interactive \
             --tty \
             $(crowdr_fullname $1) /custom/shell
    else 
        $crowdr_debug docker exec \
             --interactive \
             --tty \
             $(crowdr_fullname $1) bash
    fi
}

crowdr_command_exec() {
    if <Specific container> then
        $crowdr_debug docker exec \
             --interactive \
             --tty \
             $(crowdr_fullname $1) /custom/exec
    else 
        $crowdr_debug docker exec \
             --interactive \
             --tty \
             $(crowdr_fullname $1) bash
    fi
}

crowdr_main $@
```

> Code just as an illustration

Additionally, for building, I would like to use `https://github.com/GoogleContainerTools/kaniko`, which I then just can change the `crowdr_command_build` function

**Comment by polonskiy** [comment]
Wow. Very interesting idea.
Your pull request will be appreciated.

**Comment by BitFis** [comment]
I created the merge request, feel free to comment on any issues
