### ISSUE TITLE
Wondering what to do with my project

### ISSUE THREAD

**Issue by byrnedo** [polonskiy/crowdr#28]
Hi!
I wrote a port of crowdr in go a few years ago (and used it quite a bit in production for a year or two).
[github.com/byrnedo/capitan
](https://github.com/byrnedo/capitan)
I'm thinking of archiving the project, but just wanted to reach out if you felt like it was something you wanted to take over?

**Comment by polonskiy** [comment]
Hello.
>  I wrote a port of crowdr in go a few years ago (and used it quite a bit in production for a year or two).

Glad to see that my humble experiment inspired someone.

>  I'm thinking of archiving the project, but just wanted to reach out if you felt like it was something you wanted to take over?

No. Thank you.
